# Generated by Django 4.2 on 2023-04-16 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('password1', models.CharField(max_length=15)),
                ('password2', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=3)),
                ('aadhaar', models.CharField(max_length=12)),
                ('addr_line', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=6)),
                ('medical_history', models.TextField(max_length=200)),
                ('social_history', models.TextField(max_length=200)),
                ('agreement', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='cpassword',
            new_name='password2',
        ),
    ]
