# Generated by Django 4.2 on 2023-04-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0002_donor_rename_password_recipient_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='password2',
        ),
    ]
