# Generated by Django 4.2 on 2023-04-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0004_donor_district_recipient_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
