# Generated by Django 4.2 on 2023-04-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0005_alter_donor_age_alter_donor_dob_alter_recipient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
