# Generated by Django 4.2 on 2023-04-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0007_donor_email_recipient_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='password1',
            new_name='password',
        ),
    ]
