# Generated by Django 4.1.7 on 2023-04-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0008_rename_password1_donor_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='password',
        ),
    ]
