# Generated by Django 4.2 on 2023-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0009_remove_donor_agreement_remove_donor_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='organ',
            field=models.CharField(default='kidney', max_length=20),
            preserve_default=False,
        ),
    ]
