# Generated by Django 4.2 on 2023-04-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0010_recipient_organ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_checked', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='organ',
            new_name='organ_needed',
        ),
        migrations.AddField(
            model_name='donor',
            name='organ',
            field=models.ManyToManyField(related_name='organ', to='organdonation.organs'),
        ),
    ]
