# Generated by Django 4.2 on 2023-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0011_organs_rename_organ_recipient_organ_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='organ',
        ),
        migrations.RemoveField(
            model_name='organs',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='donor',
            name='organs',
            field=models.ManyToManyField(related_name='organs', to='organdonation.organs'),
        ),
    ]
