# Generated by Django 4.2 on 2023-04-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0012_remove_donor_organ_remove_organs_is_checked_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organs',
            new_name='Organ',
        ),
    ]
