# Generated by Django 4.2 on 2023-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0014_alter_donor_organs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='organs',
            field=models.ManyToManyField(related_name='donors', to='organdonation.organ'),
        ),
    ]
