# Generated by Django 4.2 on 2023-05-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0016_alter_donor_organs'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='requested_donors',
            field=models.ManyToManyField(related_name='requested_donors', to='organdonation.donor'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='aadhaar',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='aadhaar',
            field=models.CharField(max_length=16),
        ),
    ]
