# Generated by Django 4.2 on 2023-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0017_donor_request_recipient_requested_donors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='request',
            new_name='is_accepted',
        ),
        migrations.AddField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
