# Generated by Django 4.2 on 2023-05-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0020_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='requested_donors',
        ),
    ]
