# Generated by Django 4.2 on 2023-06-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0021_remove_donor_is_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_pending',
        ),
    ]
